version: '3.9'

services:
  node:
    container_name: api
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on: [postgres]
    volumes:
      - .:/usr/src/app
  postgres:
    image: postgres:15.1
    container_name: database
    logging:
      driver: none
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:${DB_PORT}
    volumes:
      - ./data:/var/lib/postgresql/data
